//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3053
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientSystem.ClientSystemServices {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ClientSystemServices.Service1Soap")]
    public interface Service1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOfficeRebate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        decimal GetOfficeRebate(string lm, int ofId, int fId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OfficeFinanceServices", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        decimal OfficeFinanceServices(string lm, int id, bool f);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addOfficeFinanceOne", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        bool addOfficeFinanceOne(string lm, ClientSystem.ClientSystemServices.OfficeFinance model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UserInFoFinanceSelect", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        decimal UserInFoFinanceSelect(string lm, int id, bool f);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UserInFoFinanceOne", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        bool UserInFoFinanceOne(string lm, ClientSystem.ClientSystemServices.UserFinance model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddSystemModel", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        int AddSystemModel(string lm, ClientSystem.ClientSystemServices.SelectMobile model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/selectSelectMobileByID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataTable selectSelectMobileByID(string lm, string scmId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/selectOneSelectStratMobile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string selectOneSelectStratMobile(string lm, string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updateOneSelectMobile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        bool updateOneSelectMobile(string lm, ClientSystem.ClientSystemServices.SelectMobile model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataTable GetList(string lm, string strWhere);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BT", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataTable BT(string lm, string c, string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ST", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataTable ST(string lm, string c, string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetX", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string GetX(string lm, int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PassOrNot", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        bool PassOrNot(string lm, int ID, string valation1, string valation2, string valation3, string n1, string n2, string n3);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateOfficeInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        bool UpdateOfficeInfo(string lm, ClientSystem.ClientSystemServices.OfficeInfo objOfficeInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_UserPwd", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string Get_UserPwd(string lm, int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OfficeLogin", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        ClientSystem.ClientSystemServices.OfficeInfo OfficeLogin(string loginName, string loginPwd, string machineMark);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddOrderMobileModel", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        int AddOrderMobileModel(string lm, ClientSystem.ClientSystemServices.OrderMobile model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/selectOrderMobileByID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataTable selectOrderMobileByID(string lm, string ormId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getnumsofordermobile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        int getnumsofordermobile(string lm, int nums);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getrebateofordermobile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        decimal getrebateofordermobile(string lm, string ofId, string funId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SelectFunctionInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataTable SelectFunctionInfo(string lm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SelectHistoryOfOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataTable SelectHistoryOfOrder(string lm, string ofId, string funId, System.DateTime dtstart, System.DateTime dtend);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class OfficeFinance : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int ofIdField;
        
        private string ofOridField;
        
        private System.DateTime ofTimeField;
        
        private int ofTypeField;
        
        private decimal ofAmountField;
        
        private decimal ofRemainAmountField;
        
        private int ofIsCurrentValueField;
        
        private int ofUserIdField;
        
        private string ofNote1Field;
        
        private string ofNote2Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ofId {
            get {
                return this.ofIdField;
            }
            set {
                this.ofIdField = value;
                this.RaisePropertyChanged("ofId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ofOrid {
            get {
                return this.ofOridField;
            }
            set {
                this.ofOridField = value;
                this.RaisePropertyChanged("ofOrid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime ofTime {
            get {
                return this.ofTimeField;
            }
            set {
                this.ofTimeField = value;
                this.RaisePropertyChanged("ofTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int ofType {
            get {
                return this.ofTypeField;
            }
            set {
                this.ofTypeField = value;
                this.RaisePropertyChanged("ofType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public decimal ofAmount {
            get {
                return this.ofAmountField;
            }
            set {
                this.ofAmountField = value;
                this.RaisePropertyChanged("ofAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public decimal ofRemainAmount {
            get {
                return this.ofRemainAmountField;
            }
            set {
                this.ofRemainAmountField = value;
                this.RaisePropertyChanged("ofRemainAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int ofIsCurrentValue {
            get {
                return this.ofIsCurrentValueField;
            }
            set {
                this.ofIsCurrentValueField = value;
                this.RaisePropertyChanged("ofIsCurrentValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int ofUserId {
            get {
                return this.ofUserIdField;
            }
            set {
                this.ofUserIdField = value;
                this.RaisePropertyChanged("ofUserId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string ofNote1 {
            get {
                return this.ofNote1Field;
            }
            set {
                this.ofNote1Field = value;
                this.RaisePropertyChanged("ofNote1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string ofNote2 {
            get {
                return this.ofNote2Field;
            }
            set {
                this.ofNote2Field = value;
                this.RaisePropertyChanged("ofNote2");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class OrderMobile : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int ormIdField;
        
        private int ormOidField;
        
        private string ormNumberField;
        
        private string ormNameField;
        
        private int ormTypeField;
        
        private int ormPayAmountField;
        
        private System.Nullable<decimal> ormRemainAmountField;
        
        private System.DateTime ormSubTimeField;
        
        private System.Nullable<System.DateTime> ormExecTimeField;
        
        private int ormStateField;
        
        private string ormPayPortField;
        
        private decimal ormRebateField;
        
        private int ormIsReValueField;
        
        private string ormNote1Field;
        
        private string ormNote2Field;
        
        private string ormNote3Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ormId {
            get {
                return this.ormIdField;
            }
            set {
                this.ormIdField = value;
                this.RaisePropertyChanged("ormId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int ormOid {
            get {
                return this.ormOidField;
            }
            set {
                this.ormOidField = value;
                this.RaisePropertyChanged("ormOid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ormNumber {
            get {
                return this.ormNumberField;
            }
            set {
                this.ormNumberField = value;
                this.RaisePropertyChanged("ormNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ormName {
            get {
                return this.ormNameField;
            }
            set {
                this.ormNameField = value;
                this.RaisePropertyChanged("ormName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int ormType {
            get {
                return this.ormTypeField;
            }
            set {
                this.ormTypeField = value;
                this.RaisePropertyChanged("ormType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int ormPayAmount {
            get {
                return this.ormPayAmountField;
            }
            set {
                this.ormPayAmountField = value;
                this.RaisePropertyChanged("ormPayAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<decimal> ormRemainAmount {
            get {
                return this.ormRemainAmountField;
            }
            set {
                this.ormRemainAmountField = value;
                this.RaisePropertyChanged("ormRemainAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public System.DateTime ormSubTime {
            get {
                return this.ormSubTimeField;
            }
            set {
                this.ormSubTimeField = value;
                this.RaisePropertyChanged("ormSubTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public System.Nullable<System.DateTime> ormExecTime {
            get {
                return this.ormExecTimeField;
            }
            set {
                this.ormExecTimeField = value;
                this.RaisePropertyChanged("ormExecTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int ormState {
            get {
                return this.ormStateField;
            }
            set {
                this.ormStateField = value;
                this.RaisePropertyChanged("ormState");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string ormPayPort {
            get {
                return this.ormPayPortField;
            }
            set {
                this.ormPayPortField = value;
                this.RaisePropertyChanged("ormPayPort");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public decimal ormRebate {
            get {
                return this.ormRebateField;
            }
            set {
                this.ormRebateField = value;
                this.RaisePropertyChanged("ormRebate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public int ormIsReValue {
            get {
                return this.ormIsReValueField;
            }
            set {
                this.ormIsReValueField = value;
                this.RaisePropertyChanged("ormIsReValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string ormNote1 {
            get {
                return this.ormNote1Field;
            }
            set {
                this.ormNote1Field = value;
                this.RaisePropertyChanged("ormNote1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string ormNote2 {
            get {
                return this.ormNote2Field;
            }
            set {
                this.ormNote2Field = value;
                this.RaisePropertyChanged("ormNote2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string ormNote3 {
            get {
                return this.ormNote3Field;
            }
            set {
                this.ormNote3Field = value;
                this.RaisePropertyChanged("ormNote3");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class OfficeInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int ofParentIdField;
        
        private int ofIdField;
        
        private string ofLoginField;
        
        private string ofPwdField;
        
        private string ofNameField;
        
        private string ofLinkmanField;
        
        private string ofPhoneField;
        
        private string ofAddressField;
        
        private string ofAreaField;
        
        private System.DateTime ofRegTimeField;
        
        private string ofStateField;
        
        private string ofNoteField;
        
        private string ofPara1Field;
        
        private string ofPara2Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ofParentId {
            get {
                return this.ofParentIdField;
            }
            set {
                this.ofParentIdField = value;
                this.RaisePropertyChanged("ofParentId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int ofId {
            get {
                return this.ofIdField;
            }
            set {
                this.ofIdField = value;
                this.RaisePropertyChanged("ofId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ofLogin {
            get {
                return this.ofLoginField;
            }
            set {
                this.ofLoginField = value;
                this.RaisePropertyChanged("ofLogin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ofPwd {
            get {
                return this.ofPwdField;
            }
            set {
                this.ofPwdField = value;
                this.RaisePropertyChanged("ofPwd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ofName {
            get {
                return this.ofNameField;
            }
            set {
                this.ofNameField = value;
                this.RaisePropertyChanged("ofName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ofLinkman {
            get {
                return this.ofLinkmanField;
            }
            set {
                this.ofLinkmanField = value;
                this.RaisePropertyChanged("ofLinkman");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string ofPhone {
            get {
                return this.ofPhoneField;
            }
            set {
                this.ofPhoneField = value;
                this.RaisePropertyChanged("ofPhone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string ofAddress {
            get {
                return this.ofAddressField;
            }
            set {
                this.ofAddressField = value;
                this.RaisePropertyChanged("ofAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string ofArea {
            get {
                return this.ofAreaField;
            }
            set {
                this.ofAreaField = value;
                this.RaisePropertyChanged("ofArea");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public System.DateTime ofRegTime {
            get {
                return this.ofRegTimeField;
            }
            set {
                this.ofRegTimeField = value;
                this.RaisePropertyChanged("ofRegTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string ofState {
            get {
                return this.ofStateField;
            }
            set {
                this.ofStateField = value;
                this.RaisePropertyChanged("ofState");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string ofNote {
            get {
                return this.ofNoteField;
            }
            set {
                this.ofNoteField = value;
                this.RaisePropertyChanged("ofNote");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string ofPara1 {
            get {
                return this.ofPara1Field;
            }
            set {
                this.ofPara1Field = value;
                this.RaisePropertyChanged("ofPara1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string ofPara2 {
            get {
                return this.ofPara2Field;
            }
            set {
                this.ofPara2Field = value;
                this.RaisePropertyChanged("ofPara2");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SelectMobile : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int scmIdField;
        
        private int scmOidField;
        
        private string scmNumberField;
        
        private int scmTypeField;
        
        private string scmNameField;
        
        private System.Nullable<decimal> scmRemainAmountField;
        
        private System.DateTime scmSubTimeField;
        
        private System.Nullable<System.DateTime> scmExecTimeField;
        
        private int scmStateField;
        
        private string scmPayPortField;
        
        private string scSelectStartField;
        
        private string scmNote1Field;
        
        private string scmNote2Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int scmId {
            get {
                return this.scmIdField;
            }
            set {
                this.scmIdField = value;
                this.RaisePropertyChanged("scmId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int scmOid {
            get {
                return this.scmOidField;
            }
            set {
                this.scmOidField = value;
                this.RaisePropertyChanged("scmOid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string scmNumber {
            get {
                return this.scmNumberField;
            }
            set {
                this.scmNumberField = value;
                this.RaisePropertyChanged("scmNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int scmType {
            get {
                return this.scmTypeField;
            }
            set {
                this.scmTypeField = value;
                this.RaisePropertyChanged("scmType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string scmName {
            get {
                return this.scmNameField;
            }
            set {
                this.scmNameField = value;
                this.RaisePropertyChanged("scmName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<decimal> scmRemainAmount {
            get {
                return this.scmRemainAmountField;
            }
            set {
                this.scmRemainAmountField = value;
                this.RaisePropertyChanged("scmRemainAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public System.DateTime scmSubTime {
            get {
                return this.scmSubTimeField;
            }
            set {
                this.scmSubTimeField = value;
                this.RaisePropertyChanged("scmSubTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public System.Nullable<System.DateTime> scmExecTime {
            get {
                return this.scmExecTimeField;
            }
            set {
                this.scmExecTimeField = value;
                this.RaisePropertyChanged("scmExecTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int scmState {
            get {
                return this.scmStateField;
            }
            set {
                this.scmStateField = value;
                this.RaisePropertyChanged("scmState");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string scmPayPort {
            get {
                return this.scmPayPortField;
            }
            set {
                this.scmPayPortField = value;
                this.RaisePropertyChanged("scmPayPort");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string scSelectStart {
            get {
                return this.scSelectStartField;
            }
            set {
                this.scSelectStartField = value;
                this.RaisePropertyChanged("scSelectStart");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string scmNote1 {
            get {
                return this.scmNote1Field;
            }
            set {
                this.scmNote1Field = value;
                this.RaisePropertyChanged("scmNote1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string scmNote2 {
            get {
                return this.scmNote2Field;
            }
            set {
                this.scmNote2Field = value;
                this.RaisePropertyChanged("scmNote2");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UserFinance : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int uIdField;
        
        private System.DateTime uTimeField;
        
        private decimal uAmountField;
        
        private decimal uRemainAmountField;
        
        private int uIsCurrentValueField;
        
        private int uUserIdField;
        
        private string uNote1Field;
        
        private string uNote2Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int UId {
            get {
                return this.uIdField;
            }
            set {
                this.uIdField = value;
                this.RaisePropertyChanged("UId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime UTime {
            get {
                return this.uTimeField;
            }
            set {
                this.uTimeField = value;
                this.RaisePropertyChanged("UTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public decimal UAmount {
            get {
                return this.uAmountField;
            }
            set {
                this.uAmountField = value;
                this.RaisePropertyChanged("UAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public decimal URemainAmount {
            get {
                return this.uRemainAmountField;
            }
            set {
                this.uRemainAmountField = value;
                this.RaisePropertyChanged("URemainAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int UIsCurrentValue {
            get {
                return this.uIsCurrentValueField;
            }
            set {
                this.uIsCurrentValueField = value;
                this.RaisePropertyChanged("UIsCurrentValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int UUserId {
            get {
                return this.uUserIdField;
            }
            set {
                this.uUserIdField = value;
                this.RaisePropertyChanged("UUserId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string UNote1 {
            get {
                return this.uNote1Field;
            }
            set {
                this.uNote1Field = value;
                this.RaisePropertyChanged("UNote1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string UNote2 {
            get {
                return this.uNote2Field;
            }
            set {
                this.uNote2Field = value;
                this.RaisePropertyChanged("UNote2");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface Service1SoapChannel : ClientSystem.ClientSystemServices.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<ClientSystem.ClientSystemServices.Service1Soap>, ClientSystem.ClientSystemServices.Service1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public decimal GetOfficeRebate(string lm, int ofId, int fId) {
            return base.Channel.GetOfficeRebate(lm, ofId, fId);
        }
        
        public decimal OfficeFinanceServices(string lm, int id, bool f) {
            return base.Channel.OfficeFinanceServices(lm, id, f);
        }
        
        public bool addOfficeFinanceOne(string lm, ClientSystem.ClientSystemServices.OfficeFinance model) {
            return base.Channel.addOfficeFinanceOne(lm, model);
        }
        
        public decimal UserInFoFinanceSelect(string lm, int id, bool f) {
            return base.Channel.UserInFoFinanceSelect(lm, id, f);
        }
        
        public bool UserInFoFinanceOne(string lm, ClientSystem.ClientSystemServices.UserFinance model) {
            return base.Channel.UserInFoFinanceOne(lm, model);
        }
        
        public int AddSystemModel(string lm, ClientSystem.ClientSystemServices.SelectMobile model) {
            return base.Channel.AddSystemModel(lm, model);
        }
        
        public System.Data.DataTable selectSelectMobileByID(string lm, string scmId) {
            return base.Channel.selectSelectMobileByID(lm, scmId);
        }
        
        public string selectOneSelectStratMobile(string lm, string type) {
            return base.Channel.selectOneSelectStratMobile(lm, type);
        }
        
        public bool updateOneSelectMobile(string lm, ClientSystem.ClientSystemServices.SelectMobile model) {
            return base.Channel.updateOneSelectMobile(lm, model);
        }
        
        public System.Data.DataTable GetList(string lm, string strWhere) {
            return base.Channel.GetList(lm, strWhere);
        }
        
        public System.Data.DataTable BT(string lm, string c, string id) {
            return base.Channel.BT(lm, c, id);
        }
        
        public System.Data.DataTable ST(string lm, string c, string id) {
            return base.Channel.ST(lm, c, id);
        }
        
        public string GetX(string lm, int ID) {
            return base.Channel.GetX(lm, ID);
        }
        
        public bool PassOrNot(string lm, int ID, string valation1, string valation2, string valation3, string n1, string n2, string n3) {
            return base.Channel.PassOrNot(lm, ID, valation1, valation2, valation3, n1, n2, n3);
        }
        
        public bool UpdateOfficeInfo(string lm, ClientSystem.ClientSystemServices.OfficeInfo objOfficeInfo) {
            return base.Channel.UpdateOfficeInfo(lm, objOfficeInfo);
        }
        
        public string Get_UserPwd(string lm, int ID) {
            return base.Channel.Get_UserPwd(lm, ID);
        }
        
        public ClientSystem.ClientSystemServices.OfficeInfo OfficeLogin(string loginName, string loginPwd, string machineMark) {
            return base.Channel.OfficeLogin(loginName, loginPwd, machineMark);
        }
        
        public int AddOrderMobileModel(string lm, ClientSystem.ClientSystemServices.OrderMobile model) {
            return base.Channel.AddOrderMobileModel(lm, model);
        }
        
        public System.Data.DataTable selectOrderMobileByID(string lm, string ormId) {
            return base.Channel.selectOrderMobileByID(lm, ormId);
        }
        
        public int getnumsofordermobile(string lm, int nums) {
            return base.Channel.getnumsofordermobile(lm, nums);
        }
        
        public decimal getrebateofordermobile(string lm, string ofId, string funId) {
            return base.Channel.getrebateofordermobile(lm, ofId, funId);
        }
        
        public System.Data.DataTable SelectFunctionInfo(string lm) {
            return base.Channel.SelectFunctionInfo(lm);
        }
        
        public System.Data.DataTable SelectHistoryOfOrder(string lm, string ofId, string funId, System.DateTime dtstart, System.DateTime dtend) {
            return base.Channel.SelectHistoryOfOrder(lm, ofId, funId, dtstart, dtend);
        }
    }
}
